version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    container_name: mock-backend-mobile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - HOST=0.0.0.0
    volumes:
      - ./src/data:/app/src/data:rw
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Development service (optional)
  api-dev:
    build:
      context: .
      dockerfile: Dockerfile
      target: base
    container_name: mock-backend-mobile-dev
    ports:
      - "3001:3000"
    environment:
      - NODE_ENV=development
      - PORT=3000
      - HOST=0.0.0.0
    volumes:
      - ./src:/app/src:rw
      - ./package.json:/app/package.json:ro
      - ./bun.lock:/app/bun.lock:ro
    command: ["bun", "run", "dev"]
    profiles:
      - dev
    restart: unless-stopped
